flock-community/flock-eco-workday

package.json
+ add homepage
+ add repository
+ add bugs
=> add additional package information

pom.xml
+ create additional properties for package/depenency versions
+ move frontend-maven-plugin configurations into correct executions scope
+ update node and npm to lts version
=> Feature pom optimize

src/main/react/application/Application.js
simplifies if one want to ever change HashRouter with BrowserRouter, only the import has to change.
=> import HashRouter as named import

.editorconfig
+ create editorconfig file for project
=> Feature editorconfig

.gitignore
accedently made it to the repository
=> remove generated file

.babelrc, jest.config.js, package-lock.json, package.json
add jest testing for react and javascript. Test or make them testable with the jest test framework. All frontend related features can now leverage jest. There are no additional tests written. This only creates the testing setup.
=> Feature testing

src/develop/kotlin/mocks/LoadAssignmentData.kt, src/develop/kotlin/mocks/LoadHolidayData.kt, src/develop/kotlin/mocks/LoadPersonData.kt, src/main/kotlin/controllers/AssignmentController.kt, src/main/kotlin/controllers/PersonController.kt, src/test/kotlin/controllers/PersonControllerTest.kt, src/test/kotlin/repository/PersonRepositoryTest.kt
+ fix mvn verfiy
+ fix linting errors
+ travis-ci tests should again pass
=> Hotfix kotlin lint

src/main/react/components/FabButtons.js
+ copy styles from ClientFeature which uses the Fab button
+ create HOC from Fab with custom styles
=> create AddActionFab Component

src/main/react/utils/validation/definedVars.js, src/main/react/utils/validation/definedVars.spec.js, src/main/react/utils/validation/index.js
+ add definedVars with isUndefined, isDefined functions
+ add test for isUndefined, isDefined functions
=> create validation utils

src/main/react/features/person/PersonDetails.js, src/main/react/features/person/PersonDialog.js, src/main/react/features/person/PersonFeature.js, src/main/react/features/person/context/PersonContext.js, src/main/react/features/person/index.js, src/main/react/features/person/table/PersonTable.js, src/main/react/features/person/widgets/Feed.js, src/main/react/utils/validation/definedVars.js, src/main/react/utils/validation/definedVars.spec.js, src/main/react/utils/validation/index.js
+ add PersonContext to store the person
+ add additional validation helper function
+ add reload, setReload states to toggle a reload 
+ refresh PersonTable on new added person from PersonDialog
+ refresh PersonDetails on changed person from PersonDialog
+ redirect user to PersonTable on delete
=> Feature person refresh

src/main/react/application/ApplicationLayout.js
=> move destructing props into function body

src/main/react/application/Application.js, src/main/react/clients/UserStatusClient.js
+ create UserStatusClient or Service to fetch the api endpoint "login/status"
+ add the UserStatusClient to the Application component and replace the fetch
=> Hotfix application login-status

.eslintrc.yaml, package-lock.json, package.json
+ add jest to eslint configurations
+ add recommend and style options for good testing practises and cleaner null handling during testing
=> Hotfix eslint jest

src/main/react/features/home/HomeFeature.js
+ remove fetch statement
+ add UserClient.findUsersMe function and setUser to return param
=> add UserClient to fetch user

src/main/react/application/Application.js
=> fix setState without override own state

src/main/react/components/transitions/Slide.js, src/main/react/features/person/PersonDialog.js
+ add a transition component TransitionSlider
+ takes a props direction which determines where the Slider slides-to
=> Feature transition components

flock-eco-workday.iml, src/main/kotlin/controllers/PersonController.kt, src/main/kotlin/forms/PersonForm.kt, src/main/kotlin/repository/PersonRepository.kt, src/main/kotlin/services/PersonService.kt, src/test/kotlin/controllers/PersonControllerTest.kt, src/test/kotlin/repository/PersonRepositoryTest.kt
+ replace the query selector for a person from id to code (how its used to)
=> Feature person id replacement 

package-lock.json, package.json
=> add nodemon + test:tdd script

src/main/react/components/PeriodForm.js
+ fix target value manipulation and set to correct passed value
=> fix PeriodForm handleChangeForm

.idea/runConfigurations/AssignmentControllerTest.xml, .idea/runConfigurations/AssignmentRepositoryTest.xml, .idea/runConfigurations/ClientControllerTest.xml, .idea/runConfigurations/ClientRepositoryTest.xml, .idea/runConfigurations/DayRepositoryTest.xml, .idea/runConfigurations/HolidayControllerTest.xml, .idea/runConfigurations/HolidayRepositoryTest.xml, .idea/runConfigurations/PeriodRepositoryTest.xml, .idea/runConfigurations/PersonControllerTest.xml, .idea/runConfigurations/PersonRepositoryTest.xml, .idea/runConfigurations/SickdayControllerTest.xml, .idea/runConfigurations/SickdayRepositoryTest.xml, .idea/runConfigurations/community_flock_eco_workday_ApplicationKt.xml, .idea/runConfigurations/flock_eco_workday__clean_package____.xml, .idea/runConfigurations/flock_eco_workday__clean_test_package____.xml, src/test/kotlin/controllers/AssignmentControllerTest.kt, src/test/kotlin/controllers/ClientControllerTest.kt, src/test/kotlin/controllers/HolidayControllerTest.kt, src/test/kotlin/repository/AssignmentRepositoryTest.kt, src/test/kotlin/repository/ClientRepositoryTest.kt, src/test/kotlin/repository/DayRepositoryTest.kt, src/test/kotlin/repository/HolidayRepositoryTest.kt, src/test/kotlin/repository/PeriodRepositoryTest.kt
+ add runConfigurations for idea
+ add tests for all repositories and controllers
+ add dummy test case to all of them
=> Feature tests&run

src/develop/kotlin/mocks/LoadPersonData.kt, src/main/kotlin/forms/PersonForm.kt, src/main/kotlin/model/Person.kt, src/main/kotlin/services/PersonService.kt, src/main/react/components/selector/PersonSelector.js, src/main/react/components/selector/UserSelector.js, src/main/react/components/selector/UserSelectorFormInput.js, src/main/react/components/selector/index.js, src/main/react/features/person/PersonForm.js, src/test/kotlin/controllers/PersonControllerTest.kt, src/test/kotlin/controllers/SickdayControllerTest.kt, src/test/kotlin/repository/PersonRepositoryTest.kt
+ create a selection to link a user to a person inside the PersonDialog --> PersonForm
+ change the PersonController and PersonService to handle user as PersonForm
+ update PersonForm/Person parameters/attributes
+ update tests for person (controller, repository) and sickday (controller)
=> Feature person user selector

src/main/kotlin/authorities/PersonAuthority.kt, src/main/kotlin/controllers/PersonController.kt, src/main/kotlin/services/PersonService.kt, src/test/kotlin/controllers/PersonControllerTest.kt, src/test/kotlin/controllers/SickdayControllerTest.kt
+ add authentication for the persons api endpoints
=> Feature persons api endpoint authentication

.babelrc, package-lock.json, package.json, src/main/react/features/person/PersonDetails.js, src/main/react/features/person/PersonDialog.js, src/main/react/features/person/PersonForm.js, src/main/react/features/person/PersonRouter.js, src/main/react/features/person/PersonService.js, src/main/react/features/person/schema.js, src/main/react/features/person/table/PersonTable.js, webpack.config.js
+ fix person queries from PersonService
+ add person schema for person and personForm
+ add additional transform functions to transform to a given schema
+ add async/await support for babel by installing transform-runtime plugin
=> Hotfix person queries from PersonService

.eslintignore, src/main/react/features/holiday/HolidayDialog.js, src/main/react/features/holiday/HolidayFeature.js, src/main/react/features/holiday/HolidayForm.js, src/main/react/features/holiday/HolidayList.js
+ enable eslinting for holiday feature
+ fix linting errors
=> Feature holiday lint enable

.idea/runConfigurations/HolidayControllerTest.xml, src/develop/kotlin/mocks/LoadHolidayData.kt, src/main/kotlin/controllers/HolidayController.kt, src/main/kotlin/forms/HolidayForm.kt, src/main/kotlin/model/Holiday.kt, src/main/kotlin/repository/HolidayRepository.kt, src/main/kotlin/services/HolidayService.kt, src/test/kotlin/controllers/HolidayControllerTest.kt, src/test/kotlin/repository/HolidayRepositoryTest.kt
+ add HolidayControllerTest
+ add HolidayRepositoryTest
+ change relation for holidays from user to person
+ update Holiday model
+ update HolidayForm
+ update HolidayService
+ update HolidayController
=> Feature holiday person relation

.idea/runConfigurations/flock_eco_workday__lint_.xml
=> create ktlint script for idea intellij

src/main/react/features/person/PersonDialog.js, src/main/react/features/person/table/PersonTable.js
+ fix reload on PersonDialog submit change
=> Hotfix PersonTable reload

.eslintignore, pom.xml, src/main/react/features/assignments/AssignmentList.js, src/main/react/features/client/ClientDialog.js, src/main/react/features/client/ClientFeature.js, src/main/react/features/client/ClientForm.js, src/main/react/features/client/ClientList.js, src/main/react/features/person/index.js, src/main/react/features/person/table/PersonTableHead.js, src/main/react/features/person/widgets/Feed.js, src/main/react/features/sickday/SickFeature.js, src/main/react/features/sickday/SickdayDialog.js
+ remove features from eslintignore file
+ fix linting errors inside the features
+ add TODO notes for all unclear linting errors and disable linting errors
=> Feature activate eslint in all features

src/develop/kotlin/mocks/LoadPersonData.kt, src/main/kotlin/forms/PersonForm.kt, src/main/kotlin/model/Person.kt, src/main/kotlin/services/PersonService.kt, src/main/react/features/person/PersonForm.js, src/main/react/features/person/schema.js, src/test/kotlin/controllers/HolidayControllerTest.kt, src/test/kotlin/controllers/PersonControllerTest.kt, src/test/kotlin/controllers/SickdayControllerTest.kt, src/test/kotlin/repository/HolidayRepositoryTest.kt, src/test/kotlin/repository/PersonRepositoryTest.kt, src/test/kotlin/repository/SickdayRepositoryTest.kt, src/test/kotlin/utils/RandomNumber.kt
+ add additional field number to capture person werknemernummer as requested
=> Feature person number

src/main/react/application/ApplicationLayout.tsx
=> Fix #204: Make header clickable

.github/workflows/gcp.yml
Deployment failed because of this
=> Fix #209: Update master to v0 in action definition file

src/main/react/index.html
This now uses the same family as the body of the rest of the app.
=> Resolve #205: Change chart font

src/main/react/components/fields/PeriodInputField.tsx, src/main/react/components/inputs/PeriodInput.tsx, src/main/react/features/period/Period.tsx, src/main/react/features/person/PersonDetails.tsx, src/main/react/features/workday/WorkDayForm.tsx, src/main/react/features/workday/WorkDayList.tsx, src/main/react/features/workday/WorkDayListItem.tsx, src/main/react/utils/DatePreset.ts
Resolves #234: Add preset buttons for date ranges to workday entry form
Resolves #235: Disable hours-only option for non-admin users in workday entry form
=> Improve workday form

src/main/react/components/selector/UserSelector.js
Use "id" instead of "code" for item key, this has been updated in core.
Also wait to set the selected value until all options are loaded to prevent warnings.
=> Fix person user selector

src/main/kotlin/controllers/TodoController.kt, src/main/react/components/fields/DatePickerField.tsx, src/main/react/components/selector/AssignmentSelector.tsx
fix sorting only for todo page and fix bug with workday datepicker
=> Wrk 45 todo sorting and pagination

package-lock.json, package.json, pom.xml, src/main/react/components/selector/PersonSelector.tsx
Installed new flock-eco version to have https://github.com/flock-community/flock-eco/pull/91 changes in the workday app.
=> Wrk 46 sort users by firstname

src/main/react/features/person/table/PersonTable.tsx, src/main/react/features/person/table/PersonTableHead.tsx
Removes the columns from the `/person `page
=> feat(PersonTableHead): remove columns holidays, clients and hours

src/main/react/features/person/table/PersonTable.tsx, src/main/react/theme/theme-light.js
- Changes clickhandler to an <a> element
- Makes the email selectable
=> feat(PersonTable): change clickhandler to proper element

src/main/kotlin/controllers/PersonController.kt, src/main/kotlin/repository/PersonRepository.kt, src/main/kotlin/services/PersonService.kt, src/main/react/clients/PersonClient.ts, src/main/react/features/person/table/PersonTable.tsx, src/test/kotlin/repository/PersonRepositoryTest.kt
=> Wrk 47 search full name

src/develop/kotlin/mocks/LoadUserData.kt, src/main/kotlin/authorities/WorkDayAuthority.kt, src/main/react/features/workday/WorkDayForm.tsx
support total hours in Workday editor for users with WorkDayAuthority.TOTAL_HOURS privileges
=> WRK-57 Total hour support for workers

src/main/react/features/expense/ExpenseDialog.tsx, src/main/react/features/expense/ExpenseFeature.tsx, src/main/react/features/sickday/SickDayDialog.tsx, src/main/react/features/sickday/SickDayFeature.tsx, src/main/react/features/workday/WorkDayDialog.tsx, src/main/react/features/workday/WorkDayFeature.tsx
=> add persons full name to fullscreen modals when logged in user is admin

src/main/react/utils/calcGrid.ts
- Fix issue with Sunday not showing up when it's the first day of the week
=> fix(DatePicker): fix issue with sunday not showing up

src/main/react/hooks/StatusHook.js, src/main/react/index.js
The result of the /bootstrap call was not properly used in the monkey-patched fetch api, implemented in https://github.com/flock-community/flock-eco-workday/pull/343
=> Fix fetch monkey-patch with Context-Person-Id

src/main/react/application/Application.tsx
…ed them on the UnauthenticatedRoute
=> WRK-142 Menubar shows on login page

src/main/react/application/Application.tsx
…ed them on the UnauthenticatedRoute
=> Menu bar shows on login page (WRK-142)

src/main/database/db/changelog/db.changelog-021-person-receive-email.yaml, src/main/database/db/changelog/db.changelog-master.yaml, src/main/kotlin/forms/PersonForm.kt, src/main/kotlin/model/Person.kt, src/main/kotlin/services/PersonService.kt, src/main/kotlin/services/SickDayService.kt, src/main/kotlin/services/email/CostExpenseMailService.kt, src/main/kotlin/services/email/EmailService.kt, src/main/kotlin/services/email/LeaveDayEmailService.kt, src/main/kotlin/services/email/MailjetService.kt, src/main/kotlin/services/email/SickDayEmailService.kt, src/main/kotlin/services/email/TravelExpenseMailService.kt, src/main/kotlin/services/email/WorkdayEmailService.kt, src/main/react/clients/PersonClient.ts, src/main/react/components/person-widget/PersonWidget.tsx, src/main/react/features/person/PersonForm.tsx, src/main/react/features/person/schema.js
Moet gemerged worden NA https://github.com/flock-community/flock-eco-workday/pull/350. Is namelijk op deze branch gebasseerd!
=> Add EmailService for SickDays (WRK-144)

src/main/kotlin/services/email/CostExpenseMailService.kt, src/main/kotlin/services/email/EmailService.kt, src/main/kotlin/services/email/LeaveDayEmailService.kt, src/main/kotlin/services/email/SickDayEmailService.kt, src/main/kotlin/services/email/TravelExpenseMailService.kt, src/main/kotlin/services/email/WorkdayEmailService.kt
=> Refactored the logging moved it up in the chain (WRK-145)

src/main/kotlin/services/email/CostExpenseMailService.kt, src/main/kotlin/services/email/EmailService.kt, src/main/kotlin/services/email/LeaveDayEmailService.kt, src/main/kotlin/services/email/SickDayEmailService.kt, src/main/kotlin/services/email/TravelExpenseMailService.kt, src/main/kotlin/services/email/WorkdayEmailService.kt
… not be blocked by person.receiveEmail
=> Sending notifications is blocked by person.receiveEmail (WRK-148)

src/main/kotlin/controllers/BootstrapController.kt, src/main/kotlin/model/AggregationLeaveDay.kt, src/main/kotlin/model/Day.kt, src/main/kotlin/services/AggregationService.kt, src/main/kotlin/services/email/CostExpenseMailService.kt, src/main/kotlin/services/email/EmailService.kt, src/main/kotlin/services/email/LeaveDayEmailService.kt, src/main/kotlin/services/email/SickDayEmailService.kt, src/main/kotlin/services/email/TravelExpenseMailService.kt, src/main/kotlin/services/email/WorkdayEmailService.kt
Running mvn clean install runs ktlint-format
=> Ktlint is ❤️

src/main/react/components/charts/LeaveDaysPerPersonChart.tsx, src/main/react/features/dashboard/DashboardFeature.tsx
=> Add Paid and Unpaid Parental leave to Holiday Chart on Dashboard (wrk-180)

src/main/kotlin/community/flock/eco/workday/services/email/WorkdayEmailService.kt, src/test/kotlin/community/flock/eco/workday/services/email/WorkdayEmailServiceTest.kt
=> have more readable workday update e-mails
